### ISSUE TITLE
INSTALL - Missing the roundcube webmail szerver setup

### ISSUE THREAD

**Issue by neszt** [helmo/roundcube-behat-checker#1]
Should I edit the
```
Given there is an roundcube server at "https://www.example.com/roundcube/"
```
section in file "features/roundcube.feature"?

**Comment by helmo** [comment]
Yes, 

From the README.md
> Edit the url and email settings in features/roundcube.feature (TODO, add these to variables.sh)

**Comment by neszt** [comment]
You are right thank you!
